// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Methods():Promise<any>;

export function SendHttpRequest(arg1:string):Promise<string>;
