// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function Methods():Promise<any>;

export function SendHttpRequest(arg1:string):Promise<main.HttpResponse>;
