// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFile() {
  return window['go']['main']['App']['GetFile']();
}

export function GetRequestDataFromFile(arg1) {
  return window['go']['main']['App']['GetRequestDataFromFile'](arg1);
}

export function ListDir() {
  return window['go']['main']['App']['ListDir']();
}

export function Methods() {
  return window['go']['main']['App']['Methods']();
}

export function SendHttpRequest(arg1) {
  return window['go']['main']['App']['SendHttpRequest'](arg1);
}

export function SetFile(arg1) {
  return window['go']['main']['App']['SetFile'](arg1);
}
