// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function Methods() {
  return window['go']['main']['App']['Methods']();
}

export function SendHttpRequest(arg1) {
  return window['go']['main']['App']['SendHttpRequest'](arg1);
}
