// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFile():Promise<string>;

export function GetRequestDataFromFile(arg1:string):Promise<main.FEReturn>;

export function ListDir():Promise<Array<main.DirEntry>>;

export function Methods():Promise<any>;

export function SendHttpRequest(arg1:string):Promise<main.HttpResponse>;

export function SetFile(arg1:string):Promise<main.FEReturn>;
